blog/models.py
from django.db import models

# Create your models here.
POST_CHOICES = (
    ('general','GENERAL'),
    ('technology','TECHNOLOGY'),
    ('science', 'SCIENCE'),
    ('news','NEWS'),
   
)

# class MyModel(models.Model):
#   color = models.CharField(max_length=6, choices=COLOR_CHOICES, default='green')


class Post(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField()
    category = models.CharField(max_length=20, choices=POST_CHOICES, default='general')

    
class News(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField() 

class Technology(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField()

class Science(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField()

class ReferenceNo(models.Model):
    ref = models.CharField(max_length=50)

# class Contact(models.Model):
#     name = models.Char
class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=80)
    address = models.CharField(max_length=150)
    message = models.TextField()

blog/templates/blog/about.html
{% extends 'blog/base.html' %} {% load static %} 

{% block content %}

<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<link rel = "stylesheet" href = "{% static 'blog/css/about.css' %}">

<div class="col-sm-10">
  <h3 class="text-white my-5">About Page</h3>

  <div class = "row">
    <div class="col-sm-10">
        <p>
          This is a platform made for providing the updates about Technology, Science and News.
          Here the contents are regularly updated to keep the users aware of the inside happening 
          around the globe. 
          The contents of the website are published by the members of the website. 
        </p>
    </div>
  </div>
  
  <div class = "row">
    <div class = "col-sm-5">
      <p>
        <h3><b>Developer</b></h3>
        Abhishek Kumar
      </p>
    </div>
  </div>

  <div class="row">
    <h3><b>Contacts</b></h3>
      
        <p>+91-8651246420</p>
      
      
        <p>abhishekumar2k23@gmail.com</p>
      
  </div>
  <div class = "row" >
    <h3><b>Connect With Me</b></h3>
      <div class = "col-sm-2">
      <a class="social-icon" href = "https://www.linkedin.com/in/abhishek-kumar-6227731b5" target = "_blank"> <ion-icon name="logo-linkedin"></ion-icon></a>
      </div>
      <div class = "col-sm-2">
        <a class="social-icon" href = "https://wa.me/918651246420" target = "_blank"><ion-icon name="logo-whatsapp"></ion-icon></a>
      </div>
      <div class = "col-sm-2">
        <a class="social-icon" href = "https://twitter.com/Abhi_is_me" target = "_blank"><ion-icon name="logo-twitter"></ion-icon></a>
      </div>
      <div class = "col-sm-2">
        <a class="social-icon" href = "https://www.instagram.com/abhi_is_me" target = "_blank"><ion-icon name="logo-instagram"></ion-icon></a>
      </div>
    
    </div>
    

{% endblock content %}

blog/templates/blog/addpost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class = "text-white my-5"> Dashboard/ Add Post</h3>

    <form action = "" method="POST" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type = "submit" value = "Add" class="btn btn-success">
        <a href = {% url 'dashboard' %} class = "btn btn-danger">Cancel</a>
        
    </form>
</div>
{% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "stylesheet" href = "{% static 'blog/css/bootstrap.min.css' %}">
    <link rel = "stylesheet" href = "{% static 'blog/css/style.css' %}"
    
</head>
<body>
    <div class = "container-fluid bg-dark">
    {% include 'blog/navbar.html' %}
    </div>
    <div class = "container">
        <div class = "row">
            <div class = "col-sm-12"> 
                {% block msg %}
                {% endblock msg %}
            </div>
        </div>

        <div class = "row">
            {% block side %}
            {% endblock side %}

            {% block content %}
            {% endblock content %}
        </div>
    </div>  
    {% comment %} container ends  {% endcomment %}
    <script src = "{% static 'blog/js/jquery.js' %}"></script>
    <script src = "{% static 'blog/js/popper.js' %}"></script>
    <script src = "{% static 'blog/js/bootstrap.js' %}"></script>
</body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %} {% load static %} 
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white mt-5">Contact Page</h3>

    
        {% comment %} <form action = "" method = "POST" novalidate>
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group col-md-6">
                {{fm.label_tag}} {{fm}} <small class="text-warning"> {{fm.errors|striptags}}</small>
            </div>

            
            <div>
            {% endfor %}
            <input class ="btn btn-light mt-3" type = "submit" value = "Submit">
            {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
            <p class = "alert alert-danger my-3">{{error}}</p>
            {% endfor %}
            {% endif %}
        </form>

        <div>
            {{form.name}}
            {{form.email}}
        </div> {% endcomment %}

        {% comment %} <form action = "" method = "POST" novalidate> {% endcomment %}
            {% comment %} {% csrf_token %} {% endcomment %}
            {% comment %} {% for fm in form %} {% endcomment %}
            {% comment %} <div class="form-group col-md-6"> {% endcomment %}
                {% comment %} {{fm.label_tag}} {{fm}} <small class="text-warning"> {{fm.errors|striptags}}</small> {% endcomment %}
            {% comment %} </div> {% endcomment %}

            <form class="mt-4" method = "POST">
                {% csrf_token %}
                <div class = "row">
                    <div class="form-group col-md-6">
                        <label for="inputName" class="form-label">Name</label>
                        {% comment %} <input type="text" class="form-control" id="inputName"> {% endcomment %}
                        {{form.name}} <small class="text-warning"> {{form.errors|striptags}}</small>
                     </div>

                 <div class="form-group col-md-6">
                    <label for="inputEmail" class="form-label">Email</label>
                    {% comment %} <input type="email" class="form-control" id="inputEmail" placeholder="name@example.com"> {% endcomment %}
                    {{form.email}}
                </div>
            </div>

            <div class="form-group">
                <label for="inputAddress" class="form-label">Address</label>
                {% comment %} <input type="address" class="form-control" id="inputAddress"> {% endcomment %}
                {{form.address}}
            </div>
            <div class="form-group">
                <label for="inputEmail" class="form-label">Message</label>
                {% comment %} <textarea class="form-control" id="inputMessage" rows="3"></textarea> {% endcomment %}
                {{form.message}}
            </div>

            <button type = "submit" class="btn btn-light my-3">Send</button>
            
        </form>


    
        




    {% comment %} <form class="mt-4">
        <div class = "row">
            <div class="form-group col-md-6">
                <label for="inputName" class="form-label">Name</label>
                <input type="text" class="form-control" id="inputName">
            </div>
            <div class="form-group col-md-6">
                <label for="inputEmail" class="form-label">Email</label>
                <input type="email" class="form-control" id="inputEmail" placeholder="name@example.com">
            </div>
        </div>

        <div class="form-group">
            <label for="inputAddress" class="form-label">Address</label>
            <input type="address" class="form-control" id="inputAddress">
        </div>
        <div class="form-group">
            <label for="inputEmail" class="form-label">Message</label>
            <textarea class="form-control" id="inputMessage" rows="3"></textarea>
        </div>
        <button type = "submit" class="btn btn-light my-3">Send</button>
    </form> {% endcomment %}
</div>
  

{% endblock content %}

blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %} {% load static %} 

{% block msg %}
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class = "alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}>
  <strong>{{message}}</strong>
  <button type = "button" class = "close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
{% endblock msg %}

{% comment %} for profile {% endcomment %}

{% block side %}
<div class = "col-sm-2 text-white my-5 text-center">
  <h4 class="my-5">Profile</h4>
  <h5>{{full_name}}<h5>
    {% for group in groups %}
    <p>{{group.name}}</p>
    {% endfor %}
  </div>
  {% endblock side %}


{% block content %}

<div class="col-sm-10">
  <h3 class="text-white my-5">Dashboard Page</h3>
  <a href="{% url 'addpost' %}" class = "btn btn-success">Add Post</a>
  <h4 class = "text-center alert alert-info mt-3">Show Post Information</h4>
  {% if posts %}
  <table class = "table table-hover bg-white">
    <thead>
      <tr class="text-center">
        <th scope="col" style="width:2%">ID</th>
        <th scope="col" style="width:28%">Title</th>
        <th scope="col" style="width:55%">Description</th>
        <th scope="col" style="width:15%">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
      <tr>
          <th scope="row">{{post.id}}</th>
          <td>{{post.title}}</td>
          <td>{{post.desc}}</td>
          <td class = "text-center">
            <a href="{% url 'updatepost' post.id 'Post' %}" class="btn btn-warning btn-sm">Edit</a>
            {% if perms.blog.delete_post %}
            
            <form action = "{% url 'deletepost' post.id 'Post' %}" method = "post" class = "d-inline">
              {% csrf_token %}
              <input type = "submit" class="btn btn-danger btn-sm" value = "Delete">
            </form>
            
            {% endif %}
          </td>
      </tr>
      {% endfor %}
    </tbody>

    <tbody>
      {% for new in news %}
      <tr>
          <th scope="row">{{new.id}}</th>
          <td>{{new.title}}</td>
          <td>{{new.desc}}</td>
          <td class = "text-center">
            <a href="{% url 'updatepost' new.id 'News' %}" class="btn btn-warning btn-sm">Edit</a>
            {% if perms.blog.delete_post %}
            
            <form action = "{% url 'deletepost' new.id 'News' %}" method = "post" class = "d-inline">
              {% csrf_token %}
              <input type = "submit" class="btn btn-danger btn-sm" value = "Delete">
            </form>
            
            {% endif %}
          </td>
      </tr>
      {% endfor %}
    </tbody>


    <tbody>
      {% for t in tech %}
      <tr>
          <th scope="row">{{t.id}}</th>
          <td>{{t.title}}</td>
          <td>{{t.desc}}</td>
          <td class = "text-center">
            <a href="{% url 'updatepost' t.id 'Tech' %}" class="btn btn-warning btn-sm">Edit</a>
            {% if perms.blog.delete_post %}
            
            <form action = "{% url 'deletepost' t.id 'Tech' %}" method = "post" class = "d-inline">
              {% csrf_token %}
              <input type = "submit" class="btn btn-danger btn-sm" value = "Delete">
            </form>
            
            {% endif %}
          </td>
      </tr>
      {% endfor %}
    </tbody>

    <tbody>
      {% for sci in science %}
      <tr>
          <th scope="row">{{sci.id}}</th>
          <td>{{sci.title}}</td>
          <td>{{sci.desc}}</td>
          <td class = "text-center">
            <a href="{% url 'updatepost' sci.id 'Sci' %}" class="btn btn-warning btn-sm">Edit</a>
            {% if perms.blog.delete_post %}
            
            <form action = "{% url 'deletepost' sci.id 'Sci' %}" method = "post" class = "d-inline">
              {% csrf_token %}
              <input type = "submit" class="btn btn-danger btn-sm" value = "Delete">
            </form>
            
            {% endif %}
          </td>
      </tr>
      {% endfor %}
    </tbody>


















  </table>

{% else %}
<h4 class = "text-center alert alert-warning">No Records Found! </h4>
{% endif %}
 
</div>

{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %} {% load static %} {% block content %}

<div class="col-sm-10">
  <h3 class="text-white my-5">Home Page</h3>
  {% for post in posts %}

    <div class="jumbotron jumbotron-fluid jumbo-color">
      <div class="container">
        <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
        <p class="lead">
          {{post.desc}}
        </p>
      </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %} {% load static %} {% block content %}

<div class="col-sm-6">
  <h3 class="text-white my-5">Login Page</h3>
  <form action = "" method = "POST" novalidate>
    {% csrf_token %}
    {% for fm in form %}
    <div class="form-group">
        {{fm.label_tag}} {{fm}} <small class="text-warning"> {{fm.errors|striptags}}</small>
      </div>
    <div>
    {% endfor %}
    <input class ="btn btn-light mt-3" type = "submit" value = "Submit">
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <p class = "alert alert-danger my-3">{{error}}</p>
    {% endfor %}
    {% endif %}
</form>
</div>
<div class = "col-sm-6">
</div>

{% endblock content %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">ContentHub</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contacts</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
          {% endif %}
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Blog Contents
            </a>
            <ul class="dropdown-menu form-control" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'blogcontents' 'news' %}">News</a></li>
              <li><a class="dropdown-item" href="{% url 'blogcontents' 'tech' %}">Technology</a></li>
              <li><a class="dropdown-item" href="{% url 'blogcontents' 'science' %}">Science</a></li>
              <li><a class="dropdown-item" href="{% url 'videos' %}">Videos</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

blog/templates/blog/news.html
{% extends 'blog/base.html' %} {% load static %} {% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5">News</h3>
    {% for post in posts %}
  
      <div class="jumbotron jumbotron-fluid jumbo-color">
        <div class="container">
          <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
          <p class="lead">
            {{post.desc}}
          </p>
        </div>
      </div>
      {% endfor %}
  </div>

{% endblock content %}

 

blog/templates/blog/science.html
{% extends 'blog/base.html' %} {% load static %} {% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5">Science</h3>
    {% for post in posts %}
  
      <div class="jumbotron jumbotron-fluid jumbo-color">
        <div class="container">
          <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
          <p class="lead">
            {{post.desc}}
          </p>
        </div>
      </div>
      {% endfor %}
  </div>

{% endblock content %}

blog/templates/blog/signup.html
{% extends 'blog/base.html' %} {% load static %} {% block content %}

<div class="col-sm-6">
  <h3 class="text-white my-5">Signup Page</h3>
  {% if messages %}
  {% for message in messages %}
  <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
  {% endfor %}
  {% endif %}
<form action = "" method = "POST" novalidate>
     {% csrf_token %}
     {% for fm in form %}
     <div class="form-group">
         {{fm.label_tag}} {{fm}} <small class="text-warning"> {{fm.errors|striptags}}</small>
     </div>
     {% endfor %}
     <input class ="btn btn-light mt-3" type = "submit" value = "Submit">
     {% if form.non_field_errors %}
     {% for error in form.non_field_errors %}
     <p class = "alert alert-danger my-3">{{error}}</p>
     {% endfor %}
     {% endif %}
</form>
</div>
<div class="col-sm-6">
</div>

{% endblock content %}

blog/templates/blog/tech.html
{% extends 'blog/base.html' %} {% load static %} {% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5">Technology</h3>
    {% for post in posts %}
  
      <div class="jumbotron jumbotron-fluid jumbo-color">
        <div class="container">
          <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
          <p class="lead">
            {{post.desc}}
          </p>
        </div>
      </div>
      {% endfor %}
  </div>

{% endblock content %}

blog/templates/blog/updatepost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class = "text-white my-5"> Dashboard/ Update-Post</h3>

    <form action = "" method="POST" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type = "submit" value = "Add" class="btn btn-success">
        <a href = {% url 'dashboard' %} class = "btn btn-danger">Cancel</a>
    </form>
</div>
{% endblock content %}

blog/templates/blog/video_content.html
{% extends 'blog/base.html' %} {% load static %} {% block content %}

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<div class="col-sm-10">
    <div class="app_videos">
        <!-- video start -->


        <div class="video">
            <video controls autoplay src="blog/videos/video1.mp4" class="video_player"></video>

            <!-- sidebar -->
            <div class="videoSidebar">
                <div class="videoSidebar_button">
                    <span class="material-icons"> favorite_border </span>
                    <p>12</p>
                </div>
                <div class="videoSidebar_button">
                    <span class="material-icons"> chat </span>
                    <p>52</p>
                </div>
                <div class="videoSidebar_button">
                    <span class="material-icons"> share </span>
                    <p>25</p>
                </div>
            </div>

            <div class="videoFooter">
                <div class="videoFooter_text">
                    <h3>chaman Bahar</h3>
                    <p class="videoFooter_description">Best of best</p>

                    <div class="videoFooter_ticker">
                        <span class="material-icons videoFooter_icon"> audiotrack </span>
                        <marquee>Song name</marquee>
                    </div>
                </div>

                <img class="videoFooter_record" src="blog/img/img2.png" alt="/"></img>
            </div>
        </div>

        <!-- video ends -->

        <!-- video start -->
        <div class="video">
            <video controls autoplay src="blog/videos/video2.mp4" class="video_player"></video>


            <!-- sidebar -->
            <div class="videoSidebar">
                <div class="videoSidebar_button">
                    <span class="material-icons"> favorite_border </span>
                    <p>12</p>
                </div>
                <div class="videoSidebar_button">
                    <span class="material-icons"> chat </span>
                    <p>52</p>
                </div>
                <div class="videoSidebar_button">
                    <span class="material-icons"> share </span>
                    <p>25</p>
                </div>
            </div>
            <!-- footer -->
            <div class="videoFooter">
                <div class="videoFooter_text">
                    <h3>chaman Bahar</h3>
                    <p class="videoFooter_description">Best of best</p>

                    <div class="videoFooter_ticker">
                        <span class="material-icons videoFooter_icon"> audiotrack </span>
                        <marquee>Song name</marquee>
                    </div>
                </div>

                <img class="videoFooter_record" src="blog/img/img2.png" alt="/">
            </div>
        </div>
        <!-- video ends -->
    </div>

    <script>
        var videoPlaying = null;
        const onPlay = function () {
            if (videoPlaying && videoPlaying != this) {
                videoPlaying.pause();
            }
            videoPlaying = this;
        }

        const videos = document.getElementsByClassName("video_player");
        for (let i = 0; i < videos.length; i++) {
            videos[i].addEventListener("play", onPlay);
            videos[i].addEventListener('click', function () {
                if (video.paused) {
                    video.play();
                } else {
                    video.pause();
                }
            });
        }
    </script>


</div>
{% endblock content %}